apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuber
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/idanmansours-star/test.git
    targetRevision: main
    path: .
    directory:
      include: "kuber-*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
